name: Deploy Week4 to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Debug & Copy Week4 to public folder
        run: |
          echo "Listing contents of assignment/Week4:"
          ls -l assignment/Week4
          mkdir public
          cp -r assignment/Week4/* public/
          echo "Listing contents of public:"
          ls -l public

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
